#!/usr/bin/env python

# written by:
# Alex Leake https://github.com/alexleake

import rados
import json

cluster = rados.Rados(conffile='/etc/ceph/ceph.conf')

cluster.connect()

cluster_stats = cluster.get_cluster_stats()
percent_used = round(float(cluster_stats['kb_used']) / float(cluster_stats['kb']) * 100, 2) 

if percent_used < 70:
    status = 0
    status_text = "OK"
elif percent_used < 80:
    status = 1
    status_text = "WARNING"
elif percent_used < 100:
    status = 1
    status_text = "CRITICAL"
else:
    status = 3
    status_text = "UNKNOWN"

check_title = "ceph_raw_used"
value = percent_used
warn = 70
crit = 80
minm = 0
maxm = 100
status_body = "We have used {percent_used}% of the clusters RAW capacity.".format(percent_used=percent_used)

print "{status} {check_title} count={value};{warn};{crit};{minm};{maxm}; {status_text} - {status_body}".format(**vars())
