#!/usr/bin/env python

import rados
import json

cluster = rados.Rados(conffile='/etc/ceph/ceph.conf')

cluster.connect()

cluster_osd_info = json.loads(cluster.mon_command(json.dumps({"prefix": "osd stat", "format": "json-pretty"}), "")[1])

osd_total = cluster_osd_info['num_osds']
osd_up = cluster_osd_info['num_up_osds']
osd_down = osd_total - osd_up

# warn at one-third down
osd_warn = osd_total / 3

# crit at one-half down
osd_crit = osd_total / 2

if osd_down < 10:
    status = 0
    status_text = "OK"
elif osd_down <= osd_warn:
    status = 1
    status_text = "WARNING"
elif osd_down > osd_crit:
    status = 1
    status_text = "CRITICAL"
else:
    status = 3
    status_text = "UNKNOWN"

check_title = "ceph_osd_status"
value = osd_down
warn = osd_warn
crit = osd_crit
minm = 0
maxm = osd_total
status_body = "There are {osd_total} OSDs of which {osd_down} are not active.".format(**vars())

print "{status} {check_title} count={value};{warn};{crit};{minm};{maxm}; {status_text} - {status_body}".format(**vars())
